server:
  port: 8082
# DataSource Config
spring:
  config:
    import: nacos:example
#    import: optional:configserver:http://127.0.0.1:8848/
  application:
    name: example
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33306/newhope_4a_native
    # url: jdbc:mysql://host.docker.internal:33306/newhope_4a_native
    username: root
    password: 123456
    hikari:
      minimum-idle: 100
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate[globally_quoted_identifiers]: true
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
#        refresh-enabled: true
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql